name: NASA PROJECT CI
on: 
  push:
    branches:
      - main
  pull_request:
    bracnhes:
      - main
jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:   
        node-version: [16.x]
        os: [ubuntu-latest]  
    runs-on: ${{matrix.os}}
    steps:
      - name: check the latest code of our Project
        uses: actions/checkout@v2
      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - run: npm run client-install 
      - run: npm run server-install 
      - run: npm run build --prefix client