name: NASA PROJECT CI
on: 
  push:
    branches:
      - main
  pull_request:
    bracnhes:
      - main
jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - name: check the latest code of our Project
        uses: actions/checkout@v2
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm run install 
      - run: npm run build --prefix client